homeserver_from:
    url: matrix.example.com
    server_name: example.com
homeserver_to:
    url: matrix.new-example.com
    server_name: new-example.com


as_token: set here
hs_token: set here
as_id: set here

# Rooms with these user id will not be migrated (e.g. rooms from bridges)
filter_room_with: []
port: 8181
