homeserver_from:
    url: matrix.example.com
    server_name: example.com
    bot_user: "@migrationbot:example.com"
homeserver_to:
    url: matrix.new-example.com
    server_name: new-example.com
    bot_user: "@migrationbot:new-example.com"


# Rooms with these user id will not be migrated (e.g. rooms from bridges)
filter_room_with: []
port: 8181
