homeserver_from:
    url: matrix.example.com
    server_name: example.com
homeserver_to:
    url: matrix.new-example.com
    server_name: new-example.com


hs_token: Homeserver token
as_token: Appservice token
as_id: Appservice id
as_localpart: Appservice localpart

bot_username: "@mamibot:example.com"
bot_displayname: MaMi Bot

# Rooms with these user id will not be migrated (e.g. rooms from bridges)
filter_room_with: []
port: 8181
