homeserver_url: matrix.example.com
server_name: example.com

hs_token: Homeserver token
as_token: Appservice token
as_id: Appservice id
as_localpart: Appservice localpart

bot_displayname: Matrix Import Bot

# list of userids allowed to talk to the bot.
bot_allow_users: []

admin_token: admin access token

path_to_import_files: "./path/to/folder"
port: 8181

database_location: ./data/data.db
